// Banco de preguntas.
// Cada categoría tiene 5 preguntas por valor. Las preguntas van subiendo de dificultad:
// x100 = fáciles, x500 = muy difíciles. En cada partida se sortean las categorías y,
// para cada casilla, una de sus preguntas.
// "corto" es el nombre que se muestra en pantallas chicas ("-" marca dónde se puede cortar la palabra).
// La primera opción de "o" es SIEMPRE la correcta (se mezclan al mostrarse).
const VALORES = [100, 200, 300, 400, 500];

const CATEGORIAS = [
  {
    nombre: "Champions League",
    corto: "Cham-pions",
    icono: "🏆",
    preguntas: {
      100: [
        { p: "¿Qué club tiene más Copas de Europa / Champions League?", o: ["Real Madrid", "Milan", "Bayern Múnich", "Liverpool"] },
        { p: "¿Quién es el máximo goleador histórico de la Champions League?", o: ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Raúl"] },
        { p: "¿Qué club ganó la Champions 2024 en Wembley ante el Borussia Dortmund?", o: ["Real Madrid", "Bayern Múnich", "Manchester City", "Inter"] },
        { p: "¿En qué año ganó el Barcelona la Champions con el tridente Messi-Suárez-Neymar?", o: ["2015", "2011", "2009", "2016"] },
        { p: "¿Qué club ganó su primera Champions en 2025 goleando 5-0 al Inter?", o: ["PSG", "Arsenal", "Barcelona", "Bayer Leverkusen"] },
      ],
      200: [
        { p: "¿Qué equipo remontó un 0-3 y ganó la final de Estambul 2005?", o: ["Liverpool", "Milan", "Chelsea", "Manchester United"] },
        { p: "¿Qué club inglés ganó 6 Copas de Europa / Champions?", o: ["Liverpool", "Manchester United", "Chelsea", "Arsenal"] },
        { p: "¿Qué club ganó su primera Champions en 2023, ante el Inter?", o: ["Manchester City", "PSG", "Arsenal", "Napoli"] },
        { p: "¿Quién marcó un gol de chilena en la final de 2018 ante el Liverpool?", o: ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Marcelo"] },
        { p: "¿Contra quién perdió el Atlético de Madrid las finales de Champions de 2014 y 2016?", o: ["Real Madrid", "Barcelona", "Bayern Múnich", "Juventus"] },
      ],
      300: [
        { p: "¿En qué año ganó el Inter de Mourinho la Champions?", o: ["2010", "2008", "2011", "2004"] },
        { p: "¿Qué club ganó la Champions 2013 en una final alemana ante el Dortmund?", o: ["Bayern Múnich", "Schalke 04", "Bayer Leverkusen", "Wolfsburgo"] },
        { p: "¿Qué club inglés ganó la Champions 2021 ante el Manchester City?", o: ["Chelsea", "Liverpool", "Tottenham", "Arsenal"] },
        { p: "¿Qué club ganó la Champions 2019 en Madrid ante el Tottenham?", o: ["Liverpool", "Chelsea", "Ajax", "Manchester City"] },
        { p: "¿Qué club ganó la Champions 2012 por penales en Múnich, ante el Bayern?", o: ["Chelsea", "Barcelona", "Real Madrid", "Manchester United"] },
      ],
      400: [
        { p: "¿Qué club ganó la Champions 2008 en Moscú, por penales ante el Chelsea?", o: ["Manchester United", "Liverpool", "Arsenal", "Barcelona"] },
        { p: "¿Qué equipo portugués ganó la Champions 2004 dirigido por José Mourinho?", o: ["Porto", "Benfica", "Sporting de Lisboa", "Braga"] },
        { p: "¿Contra quién ganó el Manchester United la final de 1999 en el Camp Nou?", o: ["Bayern Múnich", "Juventus", "Valencia", "Borussia Dortmund"] },
        { p: "¿Qué club ganó la Champions 1995 con un plantel muy joven?", o: ["Ajax", "Milan", "Juventus", "Borussia Dortmund"] },
        { p: "¿Cuál fue el primer club francés en ganar la Champions (1993)?", o: ["Olympique de Marsella", "PSG", "Mónaco", "Lyon"] },
      ],
      500: [
        { p: "¿Qué club alemán ganó la Champions 1997 ante la Juventus?", o: ["Borussia Dortmund", "Bayern Múnich", "Werder Bremen", "Hamburgo"] },
        { p: "¿Cuál fue el primer club británico en ganar la Copa de Europa (1967)?", o: ["Celtic", "Manchester United", "Liverpool", "Rangers"] },
        { p: "¿Qué club ganó la Copa de Europa de 1991?", o: ["Estrella Roja de Belgrado", "Olympique de Marsella", "Steaua de Bucarest", "PSV Eindhoven"] },
        { p: "¿Qué club rumano ganó la Copa de Europa 1986?", o: ["Steaua de Bucarest", "Dinamo de Bucarest", "Rapid de Bucarest", "CFR Cluj"] },
        { p: "¿Qué club neerlandés ganó la Copa de Europa 1988 ante el Benfica?", o: ["PSV Eindhoven", "Ajax", "Feyenoord", "AZ Alkmaar"] },
      ],
    },
  },
  {
    nombre: "Mundial",
    corto: "Mundial",
    icono: "🌍",
    preguntas: {
      100: [
        { p: "¿Qué selección ganó el Mundial de Qatar 2022?", o: ["Argentina", "Francia", "Croacia", "Brasil"] },
        { p: "¿Qué selección tiene más Mundiales ganados?", o: ["Brasil", "Alemania", "Italia", "Argentina"] },
        { p: "¿Quién fue el capitán de Argentina campeona del Mundial 2022?", o: ["Lionel Messi", "Ángel Di María", "Nicolás Otamendi", "Rodrigo De Paul"] },
        { p: "¿Qué país organizó el Mundial 2022?", o: ["Qatar", "Arabia Saudita", "Emiratos Árabes Unidos", "Rusia"] },
        { p: "¿En qué país se jugó el Mundial 2014?", o: ["Brasil", "Sudáfrica", "Rusia", "Alemania"] },
      ],
      200: [
        { p: "¿Qué países organizan el Mundial 2026?", o: ["Estados Unidos, México y Canadá", "Estados Unidos, México y Costa Rica", "Canadá, Estados Unidos y Jamaica", "México, Colombia y Estados Unidos"] },
        { p: "¿Qué país organizó el Mundial 2018?", o: ["Rusia", "Qatar", "Brasil", "Alemania"] },
        { p: "¿Qué selección ganó el Mundial 2018?", o: ["Francia", "Croacia", "Bélgica", "Inglaterra"] },
        { p: "¿Qué arquero le tapó el mano a mano a Kolo Muani en el final del alargue de Qatar 2022?", o: ["Emiliano Martínez", "Franco Armani", "Gerónimo Rulli", "Hugo Lloris"] },
        { p: "¿Quién hizo tres goles en la final de Qatar 2022?", o: ["Kylian Mbappé", "Lionel Messi", "Olivier Giroud", "Ángel Di María"] },
      ],
      300: [
        { p: "¿Qué selección ganó el Mundial 2006 por penales ante Francia?", o: ["Italia", "Alemania", "Portugal", "Brasil"] },
        { p: "¿Quién es el máximo goleador histórico de los Mundiales?", o: ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Just Fontaine"] },
        { p: "¿Quién marcó el gol de España en la final del Mundial 2010?", o: ["Andrés Iniesta", "David Villa", "Fernando Torres", "Xavi Hernández"] },
        { p: "¿Qué país organizó el Mundial 2010, el primero en África?", o: ["Sudáfrica", "Egipto", "Marruecos", "Nigeria"] },
        { p: "¿Qué país organizó y ganó el primer Mundial, en 1930?", o: ["Uruguay", "Argentina", "Italia", "Brasil"] },
      ],
      400: [
        { p: "¿Contra quién jugó Argentina la final del Mundial 1986?", o: ["Alemania Federal", "Inglaterra", "Bélgica", "Italia"] },
        { p: "¿Quién marcó dos goles de cabeza en la final del Mundial 1998?", o: ["Zinedine Zidane", "Thierry Henry", "Emmanuel Petit", "Youri Djorkaeff"] },
        { p: "¿Quién hizo los dos goles de Brasil en la final del Mundial 2002?", o: ["Ronaldo Nazário", "Rivaldo", "Ronaldinho", "Roberto Carlos"] },
        { p: "¿Qué selección eliminó a Brasil en cuartos de final de Qatar 2022?", o: ["Croacia", "Países Bajos", "Marruecos", "Francia"] },
        { p: "¿Cuántas selecciones juegan el Mundial 2026?", o: ["48", "32", "40", "64"] },
      ],
      500: [
        { p: "¿Qué selección ganó el Mundial 1966 como local?", o: ["Inglaterra", "Alemania Federal", "Portugal", "Brasil"] },
        { p: "¿Cuál fue la primera selección africana en llegar a semifinales de un Mundial?", o: ["Marruecos", "Camerún", "Senegal", "Ghana"] },
        { p: "¿Qué selección ganó el Mundial 1954 en el llamado \"Milagro de Berna\"?", o: ["Alemania Federal", "Hungría", "Uruguay", "Suecia"] },
        { p: "¿Qué selección fue la primera campeona europea de un Mundial (1934)?", o: ["Italia", "Alemania", "Inglaterra", "Checoslovaquia"] },
        { p: "¿Cuántos goles marcó Just Fontaine en el Mundial 1958 (récord en una sola edición)?", o: ["13", "11", "10", "9"] },
      ],
    },
  },
  {
    nombre: "Libertadores",
    corto: "Liberta-dores",
    icono: "🏅",
    preguntas: {
      100: [
        { p: "¿Quién ganó la final de la Libertadores 2018 jugada en Madrid?", o: ["River Plate", "Boca Juniors", "Grêmio", "Palmeiras"] },
        { p: "¿Qué club tiene más Copas Libertadores?", o: ["Independiente", "Boca Juniors", "Peñarol", "River Plate"] },
        { p: "¿Cuántas Copas Libertadores tiene Boca Juniors?", o: ["6", "5", "7", "4"] },
        { p: "¿Qué club ganó la Libertadores 2023 en el Maracaná ante Boca?", o: ["Fluminense", "Flamengo", "Palmeiras", "Botafogo"] },
        { p: "¿Cuántas Copas Libertadores tiene River Plate?", o: ["4", "3", "5", "6"] },
      ],
      200: [
        { p: "¿Qué club argentino ganó la Libertadores 2015 ante Tigres de México?", o: ["River Plate", "Boca Juniors", "San Lorenzo", "Racing Club"] },
        { p: "¿Qué club brasileño ganó las Libertadores 2020 y 2021?", o: ["Palmeiras", "Flamengo", "Santos", "Fluminense"] },
        { p: "¿Qué club ganó la Libertadores 2019 con dos goles de Gabigol en el final?", o: ["Flamengo", "Palmeiras", "Santos", "Grêmio"] },
        { p: "¿Qué club argentino ganó su primera Libertadores en 2014?", o: ["San Lorenzo", "Lanús", "Racing Club", "Newell's Old Boys"] },
        { p: "¿Qué club ganó la Libertadores 2024 en el Monumental ante Atlético Mineiro?", o: ["Botafogo", "Fluminense", "Flamengo", "River Plate"] },
      ],
      300: [
        { p: "¿Qué club brasileño ganó la Libertadores 2022 ante Athletico Paranaense?", o: ["Flamengo", "Palmeiras", "Corinthians", "Grêmio"] },
        { p: "¿Qué club argentino ganó la Libertadores 2009 ante Cruzeiro?", o: ["Estudiantes de La Plata", "Boca Juniors", "Vélez Sarsfield", "San Lorenzo"] },
        { p: "¿Qué club argentino ganó la Libertadores 1994 ante São Paulo?", o: ["Vélez Sarsfield", "Independiente", "River Plate", "Boca Juniors"] },
        { p: "¿Qué club colombiano ganó la Libertadores 2016?", o: ["Atlético Nacional", "Once Caldas", "Millonarios", "América de Cali"] },
        { p: "¿Qué club argentino ganó tres Libertadores seguidas entre 1968 y 1970?", o: ["Estudiantes de La Plata", "Independiente", "Racing Club", "Boca Juniors"] },
      ],
      400: [
        { p: "¿Qué club ganó la primera Copa Libertadores, en 1960?", o: ["Peñarol", "Nacional", "Santos", "Independiente"] },
        { p: "¿Qué club colombiano le ganó a Boca la final de la Libertadores 2004?", o: ["Once Caldas", "Atlético Nacional", "América de Cali", "Deportivo Cali"] },
        { p: "¿Qué club argentino ganó la Libertadores 1967?", o: ["Racing Club", "Independiente", "Estudiantes de La Plata", "River Plate"] },
        { p: "¿Qué club brasileño ganó las Libertadores de 1992 y 1993?", o: ["São Paulo", "Grêmio", "Cruzeiro", "Palmeiras"] },
        { p: "¿Qué club argentino ganó la Libertadores 1985?", o: ["Argentinos Juniors", "River Plate", "Ferro Carril Oeste", "Independiente"] },
      ],
      500: [
        { p: "¿Qué club ecuatoriano ganó la Libertadores 2008?", o: ["LDU Quito", "Barcelona SC", "Emelec", "Independiente del Valle"] },
        { p: "¿Qué club paraguayo ganó la Libertadores en 1979, 1990 y 2002?", o: ["Olimpia", "Cerro Porteño", "Libertad", "Guaraní"] },
        { p: "¿Qué club uruguayo le ganó la final de la Libertadores 1988 a Newell's?", o: ["Nacional", "Peñarol", "Defensor Sporting", "Danubio"] },
        { p: "¿Qué club chileno ganó la Libertadores 1991?", o: ["Colo-Colo", "Universidad de Chile", "Universidad Católica", "Cobreloa"] },
        { p: "¿Quién es el máximo goleador histórico de la Copa Libertadores?", o: ["Alberto Spencer", "Fernando Morena", "Pedro Rocha", "Daniel Onega"] },
      ],
    },
  },
  {
    nombre: "Ligas de Europa",
    corto: "Europa",
    icono: "⚽",
    preguntas: {
      100: [
        { p: "¿Cómo se llama el estadio del Real Madrid?", o: ["Santiago Bernabéu", "Camp Nou", "Metropolitano", "Mestalla"] },
        { p: "¿Qué club inglés es conocido como \"Los Diablos Rojos\"?", o: ["Manchester United", "Liverpool", "Arsenal", "Nottingham Forest"] },
        { p: "¿Cómo se le dice al partido entre Real Madrid y Barcelona?", o: ["El Clásico", "El Derbi", "El Superclásico", "El Old Firm"] },
        { p: "¿En qué país se juega la Bundesliga?", o: ["Alemania", "Austria", "Suiza", "Países Bajos"] },
        { p: "¿Cómo se llama la primera división de Italia?", o: ["Serie A", "LaLiga", "Ligue 1", "Eredivisie"] },
      ],
      200: [
        { p: "¿Qué club es el más ganador de la Bundesliga?", o: ["Bayern Múnich", "Borussia Dortmund", "Schalke 04", "Hamburgo"] },
        { p: "¿Qué equipo fue el campeón sorpresa de la Premier League 2015-16?", o: ["Leicester City", "West Ham", "Tottenham", "Southampton"] },
        { p: "¿En qué club italiano fue ídolo Diego Maradona?", o: ["Napoli", "Roma", "Juventus", "Fiorentina"] },
        { p: "¿Qué club es el más ganador de la liga de Francia?", o: ["PSG", "Saint-Étienne", "Olympique de Marsella", "Lyon"] },
        { p: "¿Cómo se llama el estadio del Bayern Múnich?", o: ["Allianz Arena", "Signal Iduna Park", "Olympiastadion", "Veltins-Arena"] },
      ],
      300: [
        { p: "¿Qué equipo ganó la Premier League 2003-04 sin perder ningún partido?", o: ["Arsenal", "Chelsea", "Manchester United", "Liverpool"] },
        { p: "¿Qué club ganó cuatro Premier League seguidas entre 2021 y 2024?", o: ["Manchester City", "Liverpool", "Chelsea", "Arsenal"] },
        { p: "¿Qué club ganó la Bundesliga 2023-24 de forma invicta?", o: ["Bayer Leverkusen", "Bayern Múnich", "Borussia Dortmund", "RB Leipzig"] },
        { p: "¿Qué club ganó LaLiga 2013-14 dirigido por Diego Simeone?", o: ["Atlético de Madrid", "Valencia", "Sevilla", "Villarreal"] },
        { p: "¿Qué club ganó 9 títulos seguidos de la Serie A entre 2012 y 2020?", o: ["Juventus", "Inter", "Milan", "Napoli"] },
      ],
      400: [
        { p: "¿Qué club ganó la Premier League 2024-25?", o: ["Liverpool", "Arsenal", "Manchester City", "Chelsea"] },
        { p: "¿Qué club ganó la Premier 2019-20 cortando una sequía de 30 años sin ligas?", o: ["Liverpool", "Manchester City", "Chelsea", "Leicester City"] },
        { p: "¿Quién es el máximo goleador histórico de LaLiga?", o: ["Lionel Messi", "Cristiano Ronaldo", "Telmo Zarra", "Hugo Sánchez"] },
        { p: "¿Cómo se llama el clásico entre Inter y Milan?", o: ["Derby della Madonnina", "Derby d'Italia", "Derby della Capitale", "Old Firm"] },
        { p: "¿Qué club ganó la Serie A 2022-23 después de 33 años sin títulos?", o: ["Napoli", "Lazio", "Roma", "Atalanta"] },
      ],
      500: [
        { p: "¿Quién es el máximo goleador histórico de la Premier League?", o: ["Alan Shearer", "Wayne Rooney", "Harry Kane", "Thierry Henry"] },
        { p: "¿Qué club tiene más títulos de liga en Portugal?", o: ["Benfica", "Porto", "Sporting de Lisboa", "Braga"] },
        { p: "¿Cómo se llama el clásico entre Celtic y Rangers?", o: ["Old Firm", "Derby della Madonnina", "Merseyside Derby", "Der Klassiker"] },
        { p: "¿Qué club ganó la Serie A 2023-24, su título número 20?", o: ["Inter", "Milan", "Juventus", "Napoli"] },
        { p: "¿Quién es el máximo goleador histórico de la Bundesliga?", o: ["Gerd Müller", "Robert Lewandowski", "Klaus Fischer", "Jupp Heynckes"] },
      ],
    },
  },
  {
    nombre: "Leyendas",
    corto: "Leyen-das",
    icono: "⭐",
    preguntas: {
      100: [
        { p: "¿Cuál era uno de los apodos de Diego Maradona?", o: ["El Pibe de Oro", "La Pulga", "El Fenómeno", "El Káiser"] },
        { p: "¿Cuántos Balones de Oro ganó Lionel Messi?", o: ["8", "7", "6", "5"] },
        { p: "¿A qué jugador se lo conoce como \"O Rei\"?", o: ["Pelé", "Garrincha", "Zico", "Romário"] },
        { p: "¿Qué número de camiseta usaba Maradona en la Selección?", o: ["10", "9", "7", "11"] },
        { p: "¿De qué país es Cristiano Ronaldo?", o: ["Portugal", "España", "Brasil", "Italia"] },
      ],
      200: [
        { p: "¿Qué jugador brasileño es apodado \"El Fenómeno\"?", o: ["Ronaldo Nazário", "Ronaldinho", "Romário", "Rivaldo"] },
        { p: "¿Qué jugador francés le dio un cabezazo a Materazzi en la final de 2006?", o: ["Zinedine Zidane", "Thierry Henry", "Franck Ribéry", "Patrick Vieira"] },
        { p: "¿Qué brasileño ganó el Balón de Oro 2005 jugando en el Barcelona?", o: ["Ronaldinho", "Rivaldo", "Romário", "Neymar"] },
        { p: "¿En qué club inglés se hizo famoso David Beckham?", o: ["Manchester United", "Chelsea", "Arsenal", "Liverpool"] },
        { p: "¿A qué leyenda alemana se la conocía como \"El Káiser\"?", o: ["Franz Beckenbauer", "Gerd Müller", "Lothar Matthäus", "Karl-Heinz Rummenigge"] },
      ],
      300: [
        { p: "¿En qué club brasileño jugó Pelé casi toda su carrera?", o: ["Santos", "Flamengo", "Corinthians", "Botafogo"] },
        { p: "¿Qué jugador neerlandés es el gran símbolo del \"Fútbol Total\"?", o: ["Johan Cruyff", "Marco van Basten", "Ruud Gullit", "Dennis Bergkamp"] },
        { p: "¿Qué jugador croata ganó el Balón de Oro 2018?", o: ["Luka Modrić", "Ivan Rakitić", "Davor Šuker", "Mario Mandžukić"] },
        { p: "¿En qué club inglés es máximo ídolo Thierry Henry?", o: ["Arsenal", "Chelsea", "Manchester United", "Tottenham"] },
        { p: "¿Qué leyenda húngara era apodada \"Cañoncito Pum\"?", o: ["Ferenc Puskás", "Sándor Kocsis", "Nándor Hidegkuti", "Zoltán Czibor"] },
      ],
      400: [
        { p: "¿Cuál es el único arquero que ganó el Balón de Oro?", o: ["Lev Yashin", "Gianluigi Buffon", "Oliver Kahn", "Manuel Neuer"] },
        { p: "¿Qué delantero neerlandés ganó tres Balones de Oro (1988, 1989 y 1992)?", o: ["Marco van Basten", "Ruud Gullit", "Johan Cruyff", "Dennis Bergkamp"] },
        { p: "¿Qué argentino ganó dos Balones de Oro jugando en el Real Madrid en los años 50?", o: ["Alfredo Di Stéfano", "Omar Sívori", "Ferenc Puskás", "Héctor Rial"] },
        { p: "¿Qué jugador italiano era apodado \"Il Divin Codino\"?", o: ["Roberto Baggio", "Paolo Maldini", "Francesco Totti", "Alessandro Del Piero"] },
        { p: "¿Cuál es el nombre real de Pelé?", o: ["Edson Arantes do Nascimento", "Manoel Francisco dos Santos", "Arthur Antunes Coimbra", "Ronaldo Luís Nazário"] },
      ],
      500: [
        { p: "¿Qué francés ganó tres Balones de Oro seguidos (1983, 1984 y 1985)?", o: ["Michel Platini", "Zinedine Zidane", "Jean-Pierre Papin", "Just Fontaine"] },
        { p: "¿Qué jugador de Liberia ganó el Balón de Oro 1995?", o: ["George Weah", "Samuel Eto'o", "Didier Drogba", "Roger Milla"] },
        { p: "¿Quién ganó el primer Balón de Oro de la historia, en 1956?", o: ["Stanley Matthews", "Alfredo Di Stéfano", "Raymond Kopa", "Ferenc Puskás"] },
        { p: "¿Qué jugador del Benfica ganó el Balón de Oro 1965?", o: ["Eusébio", "Mário Coluna", "José Águas", "Luís Figo"] },
        { p: "¿Qué brasileño bicampeón del mundo (1958 y 1962) era llamado \"La alegría del pueblo\"?", o: ["Garrincha", "Didí", "Vavá", "Zagallo"] },
      ],
    },
  },
  {
    nombre: "Fútbol Argentino",
    corto: "Fútbol Arg.",
    icono: "🧉",
    preguntas: {
      100: [
        { p: "¿Cómo se conoce popularmente al estadio de Boca Juniors?", o: ["La Bombonera", "El Monumental", "El Cilindro", "El Gigante"] },
        { p: "¿Cómo se llama el clásico entre Boca y River?", o: ["Superclásico", "Clásico de Avellaneda", "Clásico rosarino", "Clásico platense"] },
        { p: "¿Cómo se conoce al estadio de River Plate?", o: ["El Monumental", "La Bombonera", "El Nuevo Gasómetro", "La Fortaleza"] },
        { p: "¿Qué club es apodado \"El Xeneize\"?", o: ["Boca Juniors", "River Plate", "Racing Club", "San Lorenzo"] },
        { p: "¿Qué club es apodado \"El Millonario\"?", o: ["River Plate", "Boca Juniors", "Independiente", "Vélez Sarsfield"] },
      ],
      200: [
        { p: "¿Qué club es apodado \"La Academia\"?", o: ["Racing Club", "Independiente", "San Lorenzo", "Huracán"] },
        { p: "¿En qué año descendió River Plate a la B Nacional?", o: ["2011", "2009", "2012", "2010"] },
        { p: "¿Cómo se llama el clásico entre Racing e Independiente?", o: ["Clásico de Avellaneda", "Clásico del Sur", "Superclásico", "Clásico de barrio"] },
        { p: "¿Qué club argentino es conocido como \"El Rey de Copas\"?", o: ["Independiente", "Boca Juniors", "River Plate", "Estudiantes"] },
        { p: "¿Qué club es apodado \"El Pincha\"?", o: ["Estudiantes de La Plata", "Gimnasia de La Plata", "Banfield", "Lanús"] },
      ],
      300: [
        { p: "¿Qué club es apodado \"El Globo\"?", o: ["Huracán", "San Lorenzo", "Platense", "Chacarita"] },
        { p: "¿Qué club es conocido como \"El Ciclón\"?", o: ["San Lorenzo", "Huracán", "Lanús", "Banfield"] },
        { p: "¿Qué club de Rosario es apodado \"La Lepra\"?", o: ["Newell's Old Boys", "Rosario Central", "Argentino de Rosario", "Tiro Federal"] },
        { p: "¿Qué club de Rosario es apodado \"El Canalla\"?", o: ["Rosario Central", "Newell's Old Boys", "Central Córdoba", "Argentino de Rosario"] },
        { p: "¿Qué club es conocido como \"El Fortín\"?", o: ["Vélez Sarsfield", "Ferro Carril Oeste", "Argentinos Juniors", "All Boys"] },
      ],
      400: [
        { p: "¿En qué club debutó Diego Maradona como profesional?", o: ["Argentinos Juniors", "Boca Juniors", "Newell's Old Boys", "Huracán"] },
        { p: "¿Quién es el máximo goleador histórico de Boca Juniors?", o: ["Martín Palermo", "Roberto Cherro", "Francisco Varallo", "Carlos Tevez"] },
        { p: "¿Qué club argentino le ganó la Copa Intercontinental 2000 al Real Madrid?", o: ["Boca Juniors", "River Plate", "Vélez Sarsfield", "Independiente"] },
        { p: "¿Qué club es apodado \"El Granate\"?", o: ["Lanús", "Banfield", "Talleres", "Colón"] },
        { p: "¿Qué club argentino ganó la Copa Sudamericana 2013?", o: ["Lanús", "Arsenal de Sarandí", "Vélez Sarsfield", "Independiente"] },
      ],
      500: [
        { p: "¿Quién es el máximo goleador histórico del fútbol argentino de Primera División?", o: ["Arsenio Erico", "Ángel Labruna", "Martín Palermo", "Herminio Masantonio"] },
        { p: "¿Cuál fue el primer club argentino en ganar la Copa Intercontinental (1967)?", o: ["Racing Club", "Estudiantes", "Independiente", "Boca Juniors"] },
        { p: "¿Quién es el máximo goleador histórico de River Plate?", o: ["Ángel Labruna", "Bernabé Ferreyra", "Enzo Francescoli", "Oscar Más"] },
        { p: "¿Qué club argentino ganó la primera Copa Sudamericana, en 2002?", o: ["San Lorenzo", "Boca Juniors", "River Plate", "Arsenal de Sarandí"] },
        { p: "¿Qué club argentino ganó la Copa Intercontinental 1984 ante el Liverpool?", o: ["Independiente", "Argentinos Juniors", "Estudiantes", "River Plate"] },
      ],
    },
  },
  {
    nombre: "Selección Argentina",
    corto: "Selec-ción",
    icono: "💙",
    preguntas: {
      100: [
        { p: "¿Quién es el máximo goleador histórico de la Selección Argentina?", o: ["Lionel Messi", "Gabriel Batistuta", "Sergio Agüero", "Hernán Crespo"] },
        { p: "¿Quién fue el DT de Argentina campeona del Mundial 2022?", o: ["Lionel Scaloni", "Jorge Sampaoli", "Alejandro Sabella", "Gerardo Martino"] },
        { p: "¿Cuántos Mundiales ganó Argentina?", o: ["3", "2", "4", "1"] },
        { p: "¿De qué colores es la camiseta titular de la Selección Argentina?", o: ["Celeste y blanca", "Azul y amarilla", "Blanca y negra", "Celeste y azul"] },
        { p: "¿Cómo se apoda a la Selección Argentina?", o: ["La Albiceleste", "La Canarinha", "La Celeste", "La Roja"] },
      ],
      200: [
        { p: "¿A qué selección le ganó Argentina la final del Mundial 2022?", o: ["Francia", "Croacia", "Países Bajos", "Brasil"] },
        { p: "¿Quién hizo el gol de la final de la Copa América 2021 en el Maracaná?", o: ["Ángel Di María", "Lionel Messi", "Lautaro Martínez", "Rodrigo De Paul"] },
        { p: "¿Quién hizo el gol de Argentina en la final de la Copa América 2024?", o: ["Lautaro Martínez", "Julián Álvarez", "Lionel Messi", "Ángel Di María"] },
        { p: "¿A qué selección le hizo Maradona el gol de \"La Mano de Dios\"?", o: ["Inglaterra", "Bélgica", "Italia", "Alemania Federal"] },
        { p: "¿Quién pateó el último penal de la final de Qatar 2022?", o: ["Gonzalo Montiel", "Leandro Paredes", "Paulo Dybala", "Lionel Messi"] },
      ],
      300: [
        { p: "¿Quién fue el DT de Argentina campeona del Mundial 1986?", o: ["Carlos Bilardo", "César Luis Menotti", "Alfio Basile", "Daniel Passarella"] },
        { p: "¿Quién fue el goleador de Argentina en el Mundial 1978?", o: ["Mario Kempes", "Leopoldo Luque", "Daniel Bertoni", "Osvaldo Ardiles"] },
        { p: "¿Cuántas Copas América tiene Argentina?", o: ["16", "15", "14", "12"] },
        { p: "¿Contra qué selección perdió Argentina en su debut en Qatar 2022?", o: ["Arabia Saudita", "México", "Polonia", "Australia"] },
        { p: "¿Quién hizo el gol de Alemania en la final del Mundial 2014?", o: ["Mario Götze", "Thomas Müller", "André Schürrle", "Miroslav Klose"] },
      ],
      400: [
        { p: "¿Contra quién jugó Argentina la final del Mundial 1978?", o: ["Países Bajos", "Brasil", "Italia", "Alemania Federal"] },
        { p: "¿Quién fue el DT de Argentina campeona del Mundial 1978?", o: ["César Luis Menotti", "Carlos Bilardo", "Juan Carlos Lorenzo", "Osvaldo Zubeldía"] },
        { p: "¿Quién fue el DT de Argentina en el Mundial 2014?", o: ["Alejandro Sabella", "Gerardo Martino", "Diego Maradona", "Jorge Sampaoli"] },
        { p: "¿En qué Mundial debutó Lionel Messi?", o: ["Alemania 2006", "Corea-Japón 2002", "Sudáfrica 2010", "Brasil 2014"] },
        { p: "¿Qué selección eliminó a Argentina en octavos de final de Rusia 2018?", o: ["Francia", "Croacia", "Alemania", "Bélgica"] },
      ],
      500: [
        { p: "¿Quién fue el capitán de Argentina campeona en 1978?", o: ["Daniel Passarella", "Ubaldo Fillol", "Mario Kempes", "Américo Gallego"] },
        { p: "¿Quién convirtió el penal de Alemania en la final del Mundial 1990?", o: ["Andreas Brehme", "Lothar Matthäus", "Rudi Völler", "Jürgen Klinsmann"] },
        { p: "¿Qué arquero argentino fue figura atajando penales en Italia 90?", o: ["Sergio Goycochea", "Nery Pumpido", "Ubaldo Fillol", "Luis Islas"] },
        { p: "¿Quién hizo los dos goles de Argentina en la final de la Copa América 1993?", o: ["Gabriel Batistuta", "Claudio Caniggia", "Diego Simeone", "Fernando Redondo"] },
        { p: "¿Quién hizo el gol del 3-2 de Argentina en la final del Mundial 1986?", o: ["Jorge Burruchaga", "Diego Maradona", "Jorge Valdano", "José Luis Brown"] },
      ],
    },
  },
  {
    nombre: "Copa América",
    corto: "Copa América",
    icono: "🥇",
    preguntas: {
      100: [
        { p: "¿Qué selección tiene más Copas América?", o: ["Argentina", "Uruguay", "Brasil", "Chile"] },
        { p: "¿Qué selección ganó la Copa América 2021?", o: ["Argentina", "Brasil", "Colombia", "Perú"] },
        { p: "¿Qué selección perdió con Argentina la final de la Copa América 2024?", o: ["Colombia", "Uruguay", "Brasil", "Canadá"] },
        { p: "¿Qué selección perdió con Argentina la final de la Copa América 2021?", o: ["Brasil", "Colombia", "Perú", "Chile"] },
        { p: "¿En qué país se jugó la Copa América 2024?", o: ["Estados Unidos", "Brasil", "Argentina", "México"] },
      ],
      200: [
        { p: "¿Qué selección le ganó a Argentina la final de la Copa América Centenario 2016?", o: ["Chile", "Colombia", "Brasil", "Uruguay"] },
        { p: "¿Qué selección ganó su primera Copa América en 2015, como local?", o: ["Chile", "Colombia", "Perú", "Paraguay"] },
        { p: "¿En qué estadio se jugó la final de la Copa América 2021?", o: ["Maracaná", "Monumental", "Mineirão", "Centenario"] },
        { p: "¿Qué selección ganó la Copa América 2019?", o: ["Brasil", "Perú", "Argentina", "Chile"] },
        { p: "¿Qué país organizó la Copa América 2021 a último momento?", o: ["Brasil", "Argentina", "Colombia", "Chile"] },
      ],
      300: [
        { p: "¿Qué selección es la segunda con más Copas América?", o: ["Uruguay", "Brasil", "Paraguay", "Chile"] },
        { p: "¿Qué país organizó la Copa América 2019?", o: ["Brasil", "Argentina", "Chile", "Colombia"] },
        { p: "Antes de 2021, ¿en qué año había ganado Argentina su última Copa América?", o: ["1993", "1991", "1997", "2004"] },
        { p: "¿Qué selección ganó la Copa América 2011, jugada en Argentina?", o: ["Uruguay", "Paraguay", "Argentina", "Brasil"] },
        { p: "¿Qué selección le ganó a Argentina la final de la Copa América 2004 por penales?", o: ["Brasil", "Uruguay", "Colombia", "México"] },
      ],
      400: [
        { p: "¿Qué selección goleó 3-0 a Argentina en la final de la Copa América 2007?", o: ["Brasil", "Uruguay", "México", "Colombia"] },
        { p: "¿Qué selección ganó la Copa América 2001?", o: ["Colombia", "México", "Brasil", "Uruguay"] },
        { p: "¿Qué arquero fue figura de Chile campeón de la Copa América Centenario 2016?", o: ["Claudio Bravo", "Johnny Herrera", "Sergio Livingstone", "Nelson Tapia"] },
        { p: "¿Qué selección invitada perdió la final de la Copa América 2001 ante Colombia?", o: ["México", "Honduras", "Costa Rica", "Estados Unidos"] },
        { p: "¿Qué selección ganó la Copa América 1995 como local?", o: ["Uruguay", "Brasil", "Argentina", "Chile"] },
      ],
      500: [
        { p: "¿Qué selección ganó las Copas América de 1953 y 1979?", o: ["Paraguay", "Perú", "Uruguay", "Chile"] },
        { p: "¿Qué selección ganó su única Copa América en 1963, como local?", o: ["Bolivia", "Ecuador", "Venezuela", "Colombia"] },
        { p: "¿Qué selección ganó las Copas América de 1939 y 1975?", o: ["Perú", "Paraguay", "Colombia", "Chile"] },
        { p: "¿En qué año se jugó la primera Copa América (Campeonato Sudamericano)?", o: ["1916", "1930", "1924", "1910"] },
        { p: "¿Qué selección ganó la primera Copa América, en 1916?", o: ["Uruguay", "Argentina", "Brasil", "Chile"] },
      ],
    },
  },
  {
    nombre: "Técnicos",
    corto: "Técni-cos",
    icono: "📋",
    preguntas: {
      100: [
        { p: "¿Quién dirigía al Barcelona que ganó el sextete en 2009?", o: ["Pep Guardiola", "Frank Rijkaard", "Luis Enrique", "Tito Vilanova"] },
        { p: "¿Qué entrenador es apodado \"The Special One\"?", o: ["José Mourinho", "Pep Guardiola", "Carlo Ancelotti", "Jürgen Klopp"] },
        { p: "¿Qué DT argentino dirige al Atlético de Madrid desde 2011?", o: ["Diego Simeone", "Mauricio Pochettino", "Marcelo Gallardo", "Gerardo Martino"] },
        { p: "¿Qué entrenador dirigió al Manchester United durante 26 años?", o: ["Alex Ferguson", "Matt Busby", "Arsène Wenger", "Bobby Robson"] },
        { p: "¿Quién dirigió a River en la final de la Libertadores 2018 en Madrid?", o: ["Marcelo Gallardo", "Ramón Díaz", "Matías Almeyda", "Martín Demichelis"] },
      ],
      200: [
        { p: "¿Quién dirigía al Liverpool campeón de la Champions 2019?", o: ["Jürgen Klopp", "Rafa Benítez", "Brendan Rodgers", "Arne Slot"] },
        { p: "¿Qué DT italiano ganó la Champions con el Milan y con el Real Madrid?", o: ["Carlo Ancelotti", "Fabio Capello", "Arrigo Sacchi", "Marcello Lippi"] },
        { p: "¿Qué entrenador argentino es apodado \"El Loco\"?", o: ["Marcelo Bielsa", "Ricardo Gareca", "Jorge Sampaoli", "Eduardo Berizzo"] },
        { p: "¿Qué DT ganó tres Champions seguidas con el Real Madrid (2016-2018)?", o: ["Zinedine Zidane", "Carlo Ancelotti", "José Mourinho", "Rafa Benítez"] },
        { p: "¿Qué DT francés dirigió al Arsenal durante 22 años?", o: ["Arsène Wenger", "Didier Deschamps", "Gérard Houllier", "Claude Puel"] },
      ],
      300: [
        { p: "¿Qué DT llevó al Bayer Leverkusen a ganar la Bundesliga invicto en 2024?", o: ["Xabi Alonso", "Thomas Tuchel", "Julian Nagelsmann", "Hansi Flick"] },
        { p: "¿Qué DT neerlandés dirigió al Liverpool campeón de la Premier 2024-25?", o: ["Arne Slot", "Erik ten Hag", "Ronald Koeman", "Louis van Gaal"] },
        { p: "¿Qué DT ganó las Libertadores 2000, 2001 y 2003 con Boca?", o: ["Carlos Bianchi", "Miguel Ángel Russo", "Alfio Basile", "Óscar Tabárez"] },
        { p: "¿Qué DT argentino dirigió al Tottenham en la final de Champions 2019?", o: ["Mauricio Pochettino", "Diego Simeone", "Marcelo Bielsa", "Gerardo Martino"] },
        { p: "¿Quién dirigió a España campeona del Mundial 2010?", o: ["Vicente del Bosque", "Luis Aragonés", "Luis Enrique", "Julen Lopetegui"] },
      ],
      400: [
        { p: "¿Quién dirigió a Francia campeona del Mundial 2018?", o: ["Didier Deschamps", "Laurent Blanc", "Raymond Domenech", "Aimé Jacquet"] },
        { p: "¿Quién dirigió a Argentina en el Mundial 2002?", o: ["Marcelo Bielsa", "José Pékerman", "Daniel Passarella", "Alfio Basile"] },
        { p: "¿Qué DT italiano llevó al Leicester a ganar la Premier 2015-16?", o: ["Claudio Ranieri", "Carlo Ancelotti", "Antonio Conte", "Roberto Mancini"] },
        { p: "¿Quién dirigió a Alemania campeona del Mundial 2014?", o: ["Joachim Löw", "Jürgen Klinsmann", "Hansi Flick", "Franz Beckenbauer"] },
        { p: "¿Quién dirigió a Brasil campeón del Mundial 2002?", o: ["Luiz Felipe Scolari", "Carlos Alberto Parreira", "Mário Zagallo", "Tite"] },
      ],
      500: [
        { p: "¿Qué DT dirigía al Milan campeón de Europa en 1989 y 1990?", o: ["Arrigo Sacchi", "Fabio Capello", "Carlo Ancelotti", "Nils Liedholm"] },
        { p: "¿Qué DT llevó a Grecia a ganar la Eurocopa 2004?", o: ["Otto Rehhagel", "Fernando Santos", "Giovanni Trapattoni", "Guus Hiddink"] },
        { p: "¿Qué DT llevó a Estudiantes a ganar la Libertadores 1968?", o: ["Osvaldo Zubeldía", "Carlos Bilardo", "Juan Carlos Lorenzo", "Alejandro Sabella"] },
        { p: "¿Qué DT dirigió a Uruguay en los Mundiales de 2010, 2014 y 2018?", o: ["Óscar Tabárez", "Jorge Fossati", "Diego Alonso", "Marcelo Bielsa"] },
        { p: "¿Quién dirigió a Italia campeona del Mundial 2006?", o: ["Marcello Lippi", "Giovanni Trapattoni", "Cesare Prandelli", "Dino Zoff"] },
      ],
    },
  },
  {
    nombre: "Estadios",
    corto: "Esta-dios",
    icono: "🏟️",
    preguntas: {
      100: [
        { p: "¿En qué ciudad está el Camp Nou?", o: ["Barcelona", "Madrid", "Valencia", "Sevilla"] },
        { p: "¿En qué ciudad está la Bombonera?", o: ["Buenos Aires", "Rosario", "La Plata", "Córdoba"] },
        { p: "¿En qué ciudad está el estadio Maracaná?", o: ["Río de Janeiro", "São Paulo", "Brasilia", "Belo Horizonte"] },
        { p: "¿Cuál es el estadio del Manchester United?", o: ["Old Trafford", "Anfield", "Etihad Stadium", "Stamford Bridge"] },
        { p: "¿Cuál es el estadio de Londres donde juega de local la selección inglesa?", o: ["Wembley", "Old Trafford", "Anfield", "Villa Park"] },
      ],
      200: [
        { p: "¿Cuál es el estadio del Liverpool?", o: ["Anfield", "Goodison Park", "Old Trafford", "Villa Park"] },
        { p: "¿Cuál es el estadio del Chelsea?", o: ["Stamford Bridge", "Emirates Stadium", "Craven Cottage", "Selhurst Park"] },
        { p: "¿Cómo se llama el estadio que comparten Milan e Inter?", o: ["San Siro", "Olímpico", "Delle Alpi", "Diego Armando Maradona"] },
        { p: "¿En qué estadio se jugó la final del Mundial 1978?", o: ["Monumental", "La Bombonera", "Gigante de Arroyito", "Estadio Mundialista de Mar del Plata"] },
        { p: "¿En qué estadio se jugó la final River-Boca de la Libertadores 2018?", o: ["Santiago Bernabéu", "Camp Nou", "Metropolitano", "Wembley"] },
      ],
      300: [
        { p: "¿Cómo se llama el estadio del Arsenal?", o: ["Emirates Stadium", "Highbury", "Stamford Bridge", "White Hart Lane"] },
        { p: "¿En qué estadio se jugó la final del Mundial 2022?", o: ["Estadio Lusail", "Estadio Al Bayt", "Estadio 974", "Estadio Khalifa"] },
        { p: "¿Cómo se apoda el estadio de Racing Club?", o: ["El Cilindro", "El Coloso", "El Fortín", "La Fortaleza"] },
        { p: "¿Cómo se conoce al estadio de San Lorenzo?", o: ["Nuevo Gasómetro", "El Palacio", "La Bombonera", "El Monumental"] },
        { p: "¿Cómo se llama el estadio del Atlético de Madrid?", o: ["Metropolitano", "Vicente Calderón", "Santiago Bernabéu", "Vallecas"] },
      ],
      400: [
        { p: "¿En qué estadio juega de local Rosario Central?", o: ["Gigante de Arroyito", "Marcelo Bielsa", "El Cilindro", "Brigadier López"] },
        { p: "¿Cómo se llama hoy el estadio del Napoli?", o: ["Diego Armando Maradona", "San Paolo", "Olímpico", "Arechi"] },
        { p: "¿En qué estadio se jugó la final del Mundial 1986?", o: ["Estadio Azteca", "Estadio Jalisco", "Estadio Cuauhtémoc", "Estadio Universitario"] },
        { p: "¿Cuál es el estadio del Borussia Dortmund?", o: ["Signal Iduna Park", "Allianz Arena", "Veltins-Arena", "Volksparkstadion"] },
        { p: "¿En qué estadio se jugó la final del Mundial 2014?", o: ["Maracaná", "Arena Corinthians", "Mineirão", "Estadio Nacional de Brasilia"] },
      ],
      500: [
        { p: "¿En qué estadio se jugó la final del Mundial 2018?", o: ["Luzhniki", "Krestovski", "Otkrytie Arena", "Kazán Arena"] },
        { p: "¿En qué estadio se jugó la final del Mundial 1930?", o: ["Estadio Centenario", "Gran Parque Central", "Estadio Pocitos", "Monumental"] },
        { p: "¿Cómo se llama el estadio de Independiente?", o: ["Libertadores de América", "Presidente Perón", "Tomás A. Ducó", "Pedro Bidegain"] },
        { p: "¿En qué estadio se jugó la final del Mundial 2006?", o: ["Olympiastadion de Berlín", "Allianz Arena", "Westfalenstadion", "Volksparkstadion"] },
        { p: "¿Cómo se llama el estadio de Newell's Old Boys?", o: ["Marcelo Bielsa", "Gigante de Arroyito", "Lisandro de la Torre", "Jorge Newbery"] },
      ],
    },
  },
  {
    nombre: "Apodos",
    corto: "Apodos",
    icono: "🗣️",
    preguntas: {
      100: [
        { p: "¿A quién apodan \"La Pulga\"?", o: ["Lionel Messi", "Sergio Agüero", "Paulo Dybala", "Javier Saviola"] },
        { p: "¿A qué jugador se lo conoce como \"CR7\"?", o: ["Cristiano Ronaldo", "Ronaldo Nazário", "Ronaldinho", "Rafael Leão"] },
        { p: "¿A qué arquero le dicen \"Dibu\"?", o: ["Emiliano Martínez", "Franco Armani", "Sergio Romero", "Gerónimo Rulli"] },
        { p: "¿A quién le dicen \"El Toro\"?", o: ["Lautaro Martínez", "Julián Álvarez", "Nicolás Otamendi", "Enzo Fernández"] },
        { p: "¿A quién le dicen \"El Kun\"?", o: ["Sergio Agüero", "Gonzalo Higuaín", "Carlos Tevez", "Lautaro Martínez"] },
      ],
      200: [
        { p: "¿A quién le dicen \"La Joya\"?", o: ["Paulo Dybala", "Lionel Messi", "Ángel Di María", "Alejandro Garnacho"] },
        { p: "¿A quién le dicen \"El Apache\"?", o: ["Carlos Tevez", "Ariel Ortega", "Juan Román Riquelme", "Sergio Agüero"] },
        { p: "¿A quién le dicen \"El Fideo\"?", o: ["Ángel Di María", "Ezequiel Lavezzi", "Javier Pastore", "Rodrigo De Paul"] },
        { p: "¿A quién le dicen \"El Pipita\"?", o: ["Gonzalo Higuaín", "Sergio Agüero", "Carlos Tevez", "Mauro Icardi"] },
        { p: "¿A quién le dicen \"El Cholo\"?", o: ["Diego Simeone", "Fernando Redondo", "Néstor Sensini", "Juan Sebastián Verón"] },
      ],
      300: [
        { p: "¿A quién le dicen \"El Titán\"?", o: ["Martín Palermo", "Gabriel Batistuta", "Hernán Crespo", "Rodrigo Palacio"] },
        { p: "¿A qué delantero le dicen \"La Araña\"?", o: ["Julián Álvarez", "Lautaro Martínez", "Paulo Dybala", "Lucas Alario"] },
        { p: "¿A quién le dicen \"El Muñeco\"?", o: ["Marcelo Gallardo", "Ramón Díaz", "Leonardo Astrada", "Matías Almeyda"] },
        { p: "¿A qué goleador se lo conoce como \"Batigol\"?", o: ["Gabriel Batistuta", "Hernán Crespo", "Claudio Caniggia", "Abel Balbo"] },
        { p: "¿A quién le dicen \"El Payaso\"?", o: ["Pablo Aimar", "Ariel Ortega", "Juan Pablo Sorín", "Javier Saviola"] },
      ],
      400: [
        { p: "¿Qué ídolo uruguayo de River es apodado \"El Príncipe\"?", o: ["Enzo Francescoli", "Rodrigo Mora", "Rubén Paz", "Álvaro Recoba"] },
        { p: "¿A quién le dicen \"El Burrito\"?", o: ["Ariel Ortega", "Marcelo Gallardo", "Pablo Aimar", "Andrés D'Alessandro"] },
        { p: "¿A quién le dicen \"El Pájaro\"?", o: ["Claudio Caniggia", "Gabriel Batistuta", "Abel Balbo", "Ramón Díaz"] },
        { p: "¿A quién se lo conocía como \"La Saeta Rubia\"?", o: ["Alfredo Di Stéfano", "Omar Sívori", "Adolfo Pedernera", "José Manuel Moreno"] },
        { p: "¿A qué goleador de Argentina 78 se lo apodaba \"El Matador\"?", o: ["Mario Kempes", "Leopoldo Luque", "René Houseman", "Daniel Bertoni"] },
      ],
      500: [
        { p: "¿A quién le dicen \"El Bichi\"?", o: ["Claudio Borghi", "Claudio Caniggia", "Diego Latorre", "Ramón Díaz"] },
        { p: "¿A qué arquero le decían \"El Pato\" en el Mundial 78?", o: ["Ubaldo Fillol", "Héctor Baley", "Ricardo La Volpe", "Nery Pumpido"] },
        { p: "¿A qué jugador rosarino le decían \"El Trinche\"?", o: ["Tomás Carlovich", "Mario Kempes", "Marcelo Bielsa", "Ángel Di María"] },
        { p: "¿A qué ídolo de River le decían \"El Beto\"?", o: ["Norberto Alonso", "Ubaldo Fillol", "Daniel Passarella", "Leopoldo Luque"] },
        { p: "¿A qué ídolo de Independiente le dicen \"El Bocha\"?", o: ["Ricardo Bochini", "Daniel Bertoni", "Jorge Burruchaga", "Ricardo Pavoni"] },
      ],
    },
  },
  {
    nombre: "Récords y Curiosidades",
    corto: "Récords",
    icono: "📊",
    preguntas: {
      100: [
        { p: "¿Cuántos jugadores tiene cada equipo en cancha al inicio de un partido?", o: ["11", "10", "12", "9"] },
        { p: "¿Cuántos minutos dura un partido reglamentario (sin descuento)?", o: ["90", "80", "100", "120"] },
        { p: "¿Qué color de tarjeta significa expulsión?", o: ["Roja", "Amarilla", "Verde", "Azul"] },
        { p: "¿A cuántos metros del arco se patea un penal?", o: ["11", "9", "12", "16,5"] },
        { p: "¿Cada cuántos años se juega el Mundial?", o: ["4", "2", "3", "5"] },
      ],
      200: [
        { p: "¿Qué se cobra si un defensor toca la pelota con la mano a propósito dentro de su área?", o: ["Penal", "Tiro libre indirecto", "Saque de arco", "Córner"] },
        { p: "¿Cómo se llama el sistema de video que revisa jugadas?", o: ["VAR", "GPS", "Ojo de Halcón", "TMO"] },
        { p: "¿Cuántos cambios puede hacer cada equipo en un partido oficial, según la regla actual?", o: ["5", "3", "4", "6"] },
        { p: "¿Cuánto dura cada tiempo suplementario?", o: ["15 minutos", "10 minutos", "20 minutos", "30 minutos"] },
        { p: "¿Qué selección ganó la Eurocopa 2024?", o: ["España", "Inglaterra", "Francia", "Alemania"] },
      ],
      300: [
        { p: "¿Qué selección ganó la Eurocopa 2016?", o: ["Portugal", "Francia", "Alemania", "España"] },
        { p: "¿Cómo terminó Brasil-Alemania en la semifinal del Mundial 2014?", o: ["1-7", "0-5", "2-6", "1-4"] },
        { p: "¿Qué selección ganó la Eurocopa 2020, jugada en 2021?", o: ["Italia", "Inglaterra", "España", "Dinamarca"] },
        { p: "¿Quién es el máximo goleador de la historia en partidos de selecciones?", o: ["Cristiano Ronaldo", "Lionel Messi", "Ali Daei", "Pelé"] },
        { p: "¿Qué jugador ganó más Mundiales como futbolista (3)?", o: ["Pelé", "Garrincha", "Cafú", "Diego Maradona"] },
      ],
      400: [
        { p: "¿Quién es el jugador con más partidos en la historia de los Mundiales?", o: ["Lionel Messi", "Lothar Matthäus", "Miroslav Klose", "Cristiano Ronaldo"] },
        { p: "¿Qué selección ganó sorpresivamente la Eurocopa 2004?", o: ["Grecia", "Portugal", "Dinamarca", "República Checa"] },
        { p: "¿Cuántas medallas de oro olímpicas tiene Argentina en fútbol masculino?", o: ["2", "1", "3", "0"] },
        { p: "¿Quién le hizo 5 goles al Bayer Leverkusen en un partido de Champions en 2012?", o: ["Lionel Messi", "Luiz Adriano", "Robert Lewandowski", "Cristiano Ronaldo"] },
        { p: "¿En qué Mundial se usaron por primera vez las tarjetas amarilla y roja?", o: ["México 1970", "Inglaterra 1966", "Alemania 1974", "Argentina 1978"] },
      ],
      500: [
        { p: "¿Qué selección africana ganó el oro olímpico en Atlanta 1996?", o: ["Nigeria", "Camerún", "Ghana", "Senegal"] },
        { p: "¿Qué selección ganó la primera Eurocopa, en 1960?", o: ["Unión Soviética", "Yugoslavia", "España", "Francia"] },
        { p: "¿En qué año se fundó la FIFA?", o: ["1904", "1930", "1886", "1920"] },
        { p: "¿Quién hizo el gol más rápido de la historia de los Mundiales (11 segundos)?", o: ["Hakan Şükür", "Clint Dempsey", "Bryan Robson", "Václav Mašek"] },
        { p: "¿Qué selección ganó el primer Mundial femenino, en 1991?", o: ["Estados Unidos", "Noruega", "Alemania", "China"] },
      ],
    },
  },
  {
    nombre: "Eurocopa",
    corto: "Euro-copa",
    icono: "🎖️",
    preguntas: {
      100: [
        { p: "¿Cada cuántos años se juega la Eurocopa?", o: ["4", "2", "3", "5"] },
        { p: "¿Qué selección le ganó a Inglaterra la final de la Euro 2024?", o: ["España", "Francia", "Países Bajos", "Alemania"] },
        { p: "¿Qué país organizó la Eurocopa 2024?", o: ["Alemania", "Francia", "Inglaterra", "Italia"] },
        { p: "¿Quién era el capitán de Portugal campeón de la Euro 2016?", o: ["Cristiano Ronaldo", "Pepe", "Nani", "João Moutinho"] },
        { p: "¿Qué selección perdió por penales la final de la Euro 2020 en Wembley?", o: ["Inglaterra", "Italia", "España", "Dinamarca"] },
      ],
      200: [
        { p: "¿Qué selección ganó las Eurocopas de 2008 y 2012?", o: ["España", "Alemania", "Italia", "Francia"] },
        { p: "¿A qué selección le ganó Portugal la final de la Euro 2016?", o: ["Francia", "Alemania", "Gales", "Croacia"] },
        { p: "¿Qué selección tiene más Eurocopas?", o: ["España", "Alemania", "Italia", "Francia"] },
        { p: "¿Quién es el máximo goleador de la historia de las Eurocopas?", o: ["Cristiano Ronaldo", "Michel Platini", "Alan Shearer", "Antoine Griezmann"] },
        { p: "¿Qué español fue elegido mejor jugador joven de la Euro 2024?", o: ["Lamine Yamal", "Pedri", "Nico Williams", "Gavi"] },
      ],
      300: [
        { p: "¿Qué selección ganó la Euro 1992 después de entrar como reemplazo de Yugoslavia?", o: ["Dinamarca", "Suecia", "Países Bajos", "Alemania"] },
        { p: "¿Qué selección ganó la Eurocopa 2000, jugada en Bélgica y Países Bajos?", o: ["Francia", "Italia", "Países Bajos", "Portugal"] },
        { p: "¿Qué selección ganó la Eurocopa 1996, jugada en Inglaterra?", o: ["Alemania", "Inglaterra", "República Checa", "Francia"] },
        { p: "¿Qué selección ganó la Euro 1988 con una volea de Van Basten en la final?", o: ["Países Bajos", "Alemania Federal", "Italia", "Unión Soviética"] },
        { p: "¿Quién hizo el gol de España en la final de la Euro 2008?", o: ["Fernando Torres", "David Villa", "Xavi Hernández", "Cesc Fàbregas"] },
      ],
      400: [
        { p: "¿Quién hizo el gol de Portugal en el alargue de la final de la Euro 2016?", o: ["Éder", "Cristiano Ronaldo", "Nani", "Ricardo Quaresma"] },
        { p: "¿Quién hizo el \"gol de oro\" de Francia en la final de la Euro 2000?", o: ["David Trezeguet", "Thierry Henry", "Sylvain Wiltord", "Zinedine Zidane"] },
        { p: "¿Qué selección ganó la Eurocopa 1984 como local?", o: ["Francia", "España", "Alemania Federal", "Dinamarca"] },
        { p: "¿Qué selección ganó la Eurocopa 1964 como local?", o: ["España", "Italia", "Unión Soviética", "Francia"] },
        { p: "¿Qué selección perdió como local la final de la Euro 2004 ante Grecia?", o: ["Portugal", "República Checa", "Francia", "Países Bajos"] },
      ],
      500: [
        { p: "¿Cuántos goles hizo Michel Platini en la Euro 1984, todavía récord en una edición?", o: ["9", "7", "6", "11"] },
        { p: "¿Qué jugador inventó el penal picado en la final de la Euro 1976?", o: ["Antonín Panenka", "Pavel Nedvěd", "Josef Masopust", "Ivo Viktor"] },
        { p: "¿Qué selección ganó la Eurocopa 1972?", o: ["Alemania Federal", "Unión Soviética", "Bélgica", "Hungría"] },
        { p: "¿Qué selección ganó la Eurocopa 1968 como local?", o: ["Italia", "Yugoslavia", "Inglaterra", "España"] },
        { p: "¿Qué país organizó la primera Eurocopa, en 1960?", o: ["Francia", "Italia", "España", "Suiza"] },
      ],
    },
  },
  {
    nombre: "Arqueros",
    corto: "Arque-ros",
    icono: "🧤",
    preguntas: {
      100: [
        { p: "¿Qué arquero era el capitán de España campeona del Mundial 2010?", o: ["Iker Casillas", "Víctor Valdés", "Pepe Reina", "David de Gea"] },
        { p: "¿Qué arquero italiano, campeón del mundo en 2006, es leyenda de la Juventus?", o: ["Gianluigi Buffon", "Gianluigi Donnarumma", "Walter Zenga", "Francesco Toldo"] },
        { p: "¿Qué arquero alemán, ídolo del Bayern, es famoso por salir jugando lejos del arco?", o: ["Manuel Neuer", "Oliver Kahn", "Marc-André ter Stegen", "Jens Lehmann"] },
        { p: "¿Qué arquero ganó el Guante de Oro del Mundial de Qatar 2022?", o: ["Emiliano Martínez", "Hugo Lloris", "Dominik Livaković", "Yassine Bounou"] },
        { p: "¿Qué arquero belga ataja en el Real Madrid desde 2018?", o: ["Thibaut Courtois", "Simon Mignolet", "Koen Casteels", "Jan Oblak"] },
      ],
      200: [
        { p: "¿Qué arquero colombiano se hizo famoso por la atajada del \"escorpión\"?", o: ["René Higuita", "Óscar Córdoba", "David Ospina", "Faryd Mondragón"] },
        { p: "¿Qué arquero paraguayo era famoso por patear tiros libres y penales?", o: ["José Luis Chilavert", "Justo Villar", "Antony Silva", "Carlos Gamarra"] },
        { p: "¿Qué arquero fue figura de River campeón de la Libertadores 2018?", o: ["Franco Armani", "Marcelo Barovero", "Germán Lux", "Augusto Batalla"] },
        { p: "¿Qué arquero colombiano fue figura de Boca en la era de Carlos Bianchi?", o: ["Óscar Córdoba", "René Higuita", "Miguel Calero", "Faryd Mondragón"] },
        { p: "¿Qué arquero brasileño ganó la Champions 2019 con el Liverpool?", o: ["Alisson Becker", "Ederson", "Júlio César", "Dida"] },
      ],
      300: [
        { p: "¿Qué arquero argentino fue campeón del mundo en México 1986?", o: ["Nery Pumpido", "Ubaldo Fillol", "Sergio Goycochea", "Luis Islas"] },
        { p: "¿Qué arquero atajaba para Brasil en el 1-7 ante Alemania en 2014?", o: ["Júlio César", "Alisson Becker", "Jefferson", "Dida"] },
        { p: "¿Qué arquero danés ganó la Euro 92 y fue ídolo del Manchester United?", o: ["Peter Schmeichel", "Kasper Schmeichel", "Thomas Sørensen", "Lars Høgh"] },
        { p: "¿Qué arquero, apodado \"Pato\", atajó en Boca campeón de la Libertadores 2007?", o: ["Roberto Abbondanzieri", "Mauricio Caranta", "Agustín Orión", "Carlos Navarro Montoya"] },
        { p: "¿Qué arquero mexicano es famoso por sus atajadas en los Mundiales?", o: ["Guillermo Ochoa", "Jorge Campos", "Oswaldo Sánchez", "Alfredo Talavera"] },
      ],
      400: [
        { p: "¿Qué arquero italiano fue campeón del mundo en 1982 con 40 años?", o: ["Dino Zoff", "Walter Zenga", "Enrico Albertosi", "Gianluigi Buffon"] },
        { p: "¿Qué arquero inglés le hizo \"la atajada del siglo\" a Pelé en el Mundial 1970?", o: ["Gordon Banks", "Peter Shilton", "David Seaman", "Ray Clemence"] },
        { p: "¿Qué arquero fue elegido mejor jugador del Mundial 2002?", o: ["Oliver Kahn", "Rüştü Reçber", "Marcos", "Iker Casillas"] },
        { p: "¿Qué arquero de Boca era apodado \"El Loco\"?", o: ["Hugo Gatti", "Carlos Navarro Montoya", "Óscar Córdoba", "Roberto Abbondanzieri"] },
        { p: "¿Qué arquero, apodado \"El Mono\", fue ídolo de Boca en los años 90?", o: ["Carlos Navarro Montoya", "Hugo Gatti", "Sergio Goycochea", "Germán Burgos"] },
      ],
      500: [
        { p: "¿Qué apodo tenía el arquero soviético Lev Yashin?", o: ["La Araña Negra", "El Gato", "El Muro", "La Pantera"] },
        { p: "¿Qué arquero tiene el récord de más goles en la historia (más de 100)?", o: ["Rogério Ceni", "José Luis Chilavert", "Jorge Campos", "René Higuita"] },
        { p: "¿Qué arquero italiano estuvo 517 minutos sin recibir goles en el Mundial 1990?", o: ["Walter Zenga", "Dino Zoff", "Gianluca Pagliuca", "Stefano Tacconi"] },
        { p: "¿Qué arquero era el titular de Uruguay campeón del mundo en 1950?", o: ["Roque Máspoli", "Ladislao Mazurkiewicz", "Enrique Ballestrero", "Obdulio Varela"] },
        { p: "¿Qué arquero atajó penales en la final de Estambul 2005 para el Liverpool?", o: ["Jerzy Dudek", "Pepe Reina", "Chris Kirkland", "Sander Westerveld"] },
      ],
    },
  },
  {
    nombre: "Goleadores",
    corto: "Golea-dores",
    icono: "🎯",
    preguntas: {
      100: [
        { p: "¿Quién es el máximo goleador de la historia del fútbol en partidos oficiales?", o: ["Cristiano Ronaldo", "Lionel Messi", "Pelé", "Josef Bican"] },
        { p: "¿Qué goleador noruego juega en el Manchester City?", o: ["Erling Haaland", "Martin Ødegaard", "Alexander Sørloth", "Ole Gunnar Solskjær"] },
        { p: "¿Quién fue el goleador del Mundial de Qatar 2022?", o: ["Kylian Mbappé", "Lionel Messi", "Julián Álvarez", "Olivier Giroud"] },
        { p: "¿Qué goleador polaco pasó del Bayern Múnich al Barcelona en 2022?", o: ["Robert Lewandowski", "Arkadiusz Milik", "Krzysztof Piątek", "Wojciech Szczęsny"] },
        { p: "¿Quién es el máximo goleador histórico de la selección de Inglaterra?", o: ["Harry Kane", "Wayne Rooney", "Bobby Charlton", "Gary Lineker"] },
      ],
      200: [
        { p: "¿Cuántos goles hizo Haaland en su primera Premier League (2022-23), récord del torneo?", o: ["36", "32", "34", "38"] },
        { p: "¿Quién fue el goleador del Mundial 2014?", o: ["James Rodríguez", "Thomas Müller", "Lionel Messi", "Neymar"] },
        { p: "¿Quién ganó la Bota de Oro del Mundial 2010?", o: ["Thomas Müller", "David Villa", "Wesley Sneijder", "Diego Forlán"] },
        { p: "¿Quién es el máximo goleador histórico del Real Madrid?", o: ["Cristiano Ronaldo", "Raúl", "Alfredo Di Stéfano", "Karim Benzema"] },
        { p: "¿Quién es el máximo goleador histórico del Barcelona?", o: ["Lionel Messi", "César Rodríguez", "Luis Suárez", "László Kubala"] },
      ],
      300: [
        { p: "¿Quién fue el goleador del Mundial 2018?", o: ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"] },
        { p: "¿Quién fue el goleador del Mundial 2002, con 8 goles?", o: ["Ronaldo Nazário", "Miroslav Klose", "Rivaldo", "Christian Vieri"] },
        { p: "¿Qué argentino batió el récord de goles en una Serie A (36) con el Napoli en 2015-16?", o: ["Gonzalo Higuaín", "Mauro Icardi", "Ezequiel Lavezzi", "Paulo Dybala"] },
        { p: "¿Cuántos goles hizo Messi en el año 2012, récord en un año calendario?", o: ["91", "86", "79", "100"] },
        { p: "¿Quién fue el goleador del Mundial 2006?", o: ["Miroslav Klose", "Hernán Crespo", "Thierry Henry", "Ronaldo Nazário"] },
      ],
      400: [
        { p: "¿Quién fue el goleador del Mundial 1998?", o: ["Davor Šuker", "Gabriel Batistuta", "Ronaldo Nazário", "Christian Vieri"] },
        { p: "¿Quién fue el goleador del Mundial 1990?", o: ["Salvatore Schillaci", "Gary Lineker", "Lothar Matthäus", "Roger Milla"] },
        { p: "¿Qué ruso hizo 5 goles en un solo partido del Mundial 1994?", o: ["Oleg Salenko", "Andrei Kanchelskis", "Igor Kolyvanov", "Valeri Karpin"] },
        { p: "¿Qué uruguayo ganó la Bota de Oro europea con el Liverpool (2014) y con el Barcelona (2016)?", o: ["Luis Suárez", "Edinson Cavani", "Diego Forlán", "Darwin Núñez"] },
        { p: "¿Quién fue el goleador del Mundial 1986?", o: ["Gary Lineker", "Diego Maradona", "Emilio Butragueño", "Careca"] },
      ],
      500: [
        { p: "¿Quién fue el goleador del Mundial 1982?", o: ["Paolo Rossi", "Karl-Heinz Rummenigge", "Zico", "Zbigniew Boniek"] },
        { p: "¿Quién fue el goleador del Mundial 1970, con 10 goles?", o: ["Gerd Müller", "Pelé", "Jairzinho", "Teófilo Cubillas"] },
        { p: "¿Quién fue el goleador del primer Mundial, en 1930?", o: ["Guillermo Stábile", "Pedro Cea", "Héctor Scarone", "Bert Patenaude"] },
        { p: "¿Quién fue el goleador del Mundial 1966, con 9 goles?", o: ["Eusébio", "Geoff Hurst", "Bobby Charlton", "Helmut Haller"] },
        { p: "¿Qué delantero austríaco de los años 30 y 40 hizo más de 800 goles oficiales?", o: ["Josef Bican", "Matthias Sindelar", "Ernst Ocwirk", "Toni Polster"] },
      ],
    },
  },
  {
    nombre: "Messi",
    corto: "Messi",
    icono: "🐐",
    preguntas: {
      100: [
        { p: "¿En qué ciudad nació Lionel Messi?", o: ["Rosario", "Buenos Aires", "Córdoba", "Santa Fe"] },
        { p: "¿En qué club europeo jugó Messi la mayor parte de su carrera?", o: ["Barcelona", "Real Madrid", "PSG", "Manchester City"] },
        { p: "¿Con qué número de camiseta es famoso Messi?", o: ["10", "19", "30", "7"] },
        { p: "¿En qué club de Estados Unidos juega Messi desde 2023?", o: ["Inter Miami", "LA Galaxy", "New York City", "Orlando City"] },
        { p: "¿En qué club francés jugó Messi entre 2021 y 2023?", o: ["PSG", "Olympique de Marsella", "Mónaco", "Lyon"] },
      ],
      200: [
        { p: "¿En las inferiores de qué club rosarino jugó Messi?", o: ["Newell's Old Boys", "Rosario Central", "Central Córdoba", "Argentino de Rosario"] },
        { p: "¿Cuántas Champions League ganó Messi?", o: ["4", "3", "5", "2"] },
        { p: "¿Cuántos goles hizo Messi en la final de Qatar 2022 (sin contar los penales)?", o: ["2", "1", "3", "0"] },
        { p: "¿Qué premio ganó Messi en los Mundiales de 2014 y 2022?", o: ["Mejor jugador del torneo", "Bota de Oro", "Mejor jugador joven", "Premio al juego limpio"] },
        { p: "¿En qué año debutó Messi en la Primera del Barcelona?", o: ["2004", "2002", "2006", "2005"] },
      ],
      300: [
        { p: "¿A qué equipo le hizo Messi su primer gol oficial con el Barcelona, en 2005?", o: ["Albacete", "Espanyol", "Getafe", "Real Madrid"] },
        { p: "¿Cuántos goles hizo Messi en LaLiga 2011-12, récord del torneo?", o: ["50", "46", "43", "52"] },
        { p: "¿En qué año ganó Messi su primer Balón de Oro?", o: ["2009", "2008", "2010", "2007"] },
        { p: "¿Por qué Messi necesitó tratamiento médico de chico?", o: ["Déficit de hormona de crecimiento", "Asma", "Una lesión de rodilla", "Problemas de visión"] },
        { p: "¿En qué Juegos Olímpicos ganó Messi la medalla de oro?", o: ["Pekín 2008", "Atenas 2004", "Londres 2012", "Río 2016"] },
      ],
      400: [
        { p: "¿A qué equipo le hizo Messi en 2007 un gol muy parecido al de Maradona a Inglaterra?", o: ["Getafe", "Espanyol", "Sevilla", "Real Madrid"] },
        { p: "¿Contra qué selección debutó Messi en la Selección mayor, siendo expulsado enseguida?", o: ["Hungría", "Paraguay", "Venezuela", "Croacia"] },
        { p: "¿Cuántos Mundiales jugó Messi hasta Qatar 2022 incluido?", o: ["5", "4", "6", "3"] },
        { p: "¿Qué DT hizo debutar a Messi en la Primera del Barcelona?", o: ["Frank Rijkaard", "Pep Guardiola", "Louis van Gaal", "Tito Vilanova"] },
        { p: "¿Qué torneo ganó Messi en 2005, siendo goleador y mejor jugador?", o: ["Mundial Sub-20", "Copa América", "Sudamericano Sub-17", "Juegos Panamericanos"] },
      ],
      500: [
        { p: "¿Sobre qué se firmó el primer compromiso de Messi con el Barcelona, en el año 2000?", o: ["Una servilleta", "Una camiseta", "Un boleto de avión", "Una pelota"] },
        { p: "¿En qué club de barrio jugó Messi de muy chico en Rosario?", o: ["Grandoli", "Malvinas", "Alumni", "Club Atlético Fisherton"] },
        { p: "¿Contra qué equipo fue el debut oficial de Messi con el Barcelona, en 2004?", o: ["Espanyol", "Albacete", "Osasuna", "Getafe"] },
        { p: "¿Qué número usó Messi en su primera temporada en el primer equipo del Barcelona?", o: ["30", "19", "10", "14"] },
        { p: "¿Quién le dio a Messi la asistencia para su primer gol oficial en el Barcelona?", o: ["Ronaldinho", "Deco", "Samuel Eto'o", "Xavi Hernández"] },
      ],
    },
  },
  {
    nombre: "Maradona",
    corto: "Mara-dona",
    icono: "🔟",
    preguntas: {
      100: [
        { p: "¿De qué club argentino era hincha Maradona y dónde se retiró?", o: ["Boca Juniors", "Argentinos Juniors", "Newell's Old Boys", "River Plate"] },
        { p: "¿En qué Mundial fue campeón Maradona?", o: ["México 1986", "Argentina 1978", "Italia 1990", "España 1982"] },
        { p: "¿Cómo se conoce el gol con la mano de Maradona a Inglaterra en 1986?", o: ["La Mano de Dios", "El Gol del Siglo", "La Palomita", "El Gol Fantasma"] },
        { p: "¿En qué año murió Diego Maradona?", o: ["2020", "2019", "2021", "2018"] },
        { p: "¿Cómo se conoce el segundo gol de Maradona a Inglaterra en 1986, gambeteando a medio equipo?", o: ["El Gol del Siglo", "La Mano de Dios", "El Gol Imposible", "La Gambeta Eterna"] },
      ],
      200: [
        { p: "¿En qué barrio se crió Maradona?", o: ["Villa Fiorito", "La Boca", "Paternal", "Villa Crespo"] },
        { p: "¿En qué club español jugó Maradona antes de llegar al Napoli?", o: ["Barcelona", "Real Madrid", "Atlético de Madrid", "Valencia"] },
        { p: "¿Cuántas ligas italianas (Scudetti) ganó Maradona con el Napoli?", o: ["2", "1", "3", "4"] },
        { p: "¿A qué selección le hizo Maradona dos goles en la semifinal de 1986?", o: ["Bélgica", "Inglaterra", "Uruguay", "Alemania Federal"] },
        { p: "¿Qué selección dirigió Maradona como DT en el Mundial 2010?", o: ["Argentina", "Emiratos Árabes", "Bolivia", "México"] },
      ],
      300: [
        { p: "¿Contra qué selección perdió Maradona la final del Mundial 1990?", o: ["Alemania Federal", "Italia", "Brasil", "Camerún"] },
        { p: "¿En qué Mundial dio positivo Maradona en un control antidoping?", o: ["Estados Unidos 1994", "Italia 1990", "México 1986", "España 1982"] },
        { p: "¿Qué copa europea ganó Maradona con el Napoli en 1989?", o: ["Copa UEFA", "Champions League", "Recopa de Europa", "Supercopa de Europa"] },
        { p: "¿En qué club de Rosario jugó Maradona en 1993?", o: ["Newell's Old Boys", "Rosario Central", "Central Córdoba", "Tiro Federal"] },
        { p: "¿Qué club mexicano dirigió Maradona en 2018-19?", o: ["Dorados de Sinaloa", "Club América", "Tijuana", "Monterrey"] },
      ],
      400: [
        { p: "¿Qué club dirigía Maradona cuando murió, en 2020?", o: ["Gimnasia y Esgrima La Plata", "Boca Juniors", "Dorados de Sinaloa", "Racing Club"] },
        { p: "¿Cómo se llamaba el equipo infantil donde se destacó Maradona?", o: ["Los Cebollitas", "Los Pibes de Oro", "Los Pumitas", "Los Bichitos Colorados"] },
        { p: "¿En qué estadio le hizo Maradona sus dos goles a Inglaterra en 1986?", o: ["Estadio Azteca", "Estadio Jalisco", "Estadio Universitario", "Estadio Cuauhtémoc"] },
        { p: "¿En qué otro club español, además del Barcelona, jugó Maradona?", o: ["Sevilla", "Valencia", "Real Betis", "Atlético de Madrid"] },
        { p: "¿Qué relator narró el \"Gol del Siglo\" con la frase \"barrilete cósmico\"?", o: ["Víctor Hugo Morales", "José María Muñoz", "Marcelo Araujo", "Mariano Closs"] },
      ],
      500: [
        { p: "¿Contra qué equipo debutó Maradona en Primera División, en 1976?", o: ["Talleres de Córdoba", "Boca Juniors", "San Lorenzo", "Huracán"] },
        { p: "¿En qué año ganó Maradona el Mundial Juvenil (Sub-20) en Japón?", o: ["1979", "1977", "1981", "1983"] },
        { p: "¿Qué club de Emiratos Árabes dirigió Maradona?", o: ["Al-Wasl", "Al-Ain", "Al-Jazira", "Al-Fujairah"] },
        { p: "¿Qué arquero inglés recibió la \"Mano de Dios\"?", o: ["Peter Shilton", "Gordon Banks", "David Seaman", "Ray Clemence"] },
        { p: "¿Qué DT hizo debutar a Maradona en Argentinos Juniors?", o: ["Juan Carlos Montes", "César Luis Menotti", "Carlos Bilardo", "Ángel Labruna"] },
      ],
    },
  },
  {
    nombre: "Reglamento",
    corto: "Regla-mento",
    icono: "🟨",
    preguntas: {
      100: [
        { p: "¿Qué color de tarjeta se usa para amonestar?", o: ["Amarilla", "Roja", "Verde", "Azul"] },
        { p: "¿Cuántas tarjetas amarillas en un mismo partido equivalen a una expulsión?", o: ["2", "3", "1", "4"] },
        { p: "¿Qué se cobra cuando la pelota sale por la línea lateral?", o: ["Saque lateral", "Córner", "Saque de arco", "Tiro libre"] },
        { p: "¿Qué se cobra cuando un defensor saca la pelota por su propia línea de fondo?", o: ["Córner", "Saque de arco", "Saque lateral", "Penal"] },
        { p: "¿Quién es el único jugador que puede tocar la pelota con la mano dentro de su área?", o: ["El arquero", "El capitán", "El líbero", "Nadie"] },
      ],
      200: [
        { p: "¿Cuántos jugadores como mínimo necesita un equipo para que siga el partido?", o: ["7", "8", "9", "6"] },
        { p: "¿A qué distancia de la pelota deben ubicarse los rivales en un tiro libre?", o: ["9,15 metros", "11 metros", "5 metros", "7 metros"] },
        { p: "¿Desde dónde se puede patear un saque de arco?", o: ["Desde cualquier punto del área chica", "Solo desde el punto penal", "Desde la línea del área grande", "Solo desde las esquinas del área chica"] },
        { p: "¿Hay offside si un jugador recibe directamente de un saque lateral?", o: ["No", "Sí", "Solo dentro del área", "Solo en el segundo tiempo"] },
        { p: "¿Qué indica el árbitro cuando levanta un brazo al cobrar un tiro libre?", o: ["Que es indirecto", "Que es directo", "Que hay ventaja", "Que terminó el tiempo"] },
      ],
      300: [
        { p: "¿Puede haber offside si el jugador está en su propio campo?", o: ["No", "Sí", "Solo si está detrás del último defensor", "Solo si el arquero salió"] },
        { p: "¿Cuánto mide de ancho el arco reglamentario?", o: ["7,32 metros", "7 metros", "8 metros", "6,50 metros"] },
        { p: "¿Cuánto mide de alto el arco reglamentario?", o: ["2,44 metros", "2,20 metros", "2,50 metros", "2,60 metros"] },
        { p: "¿Qué se cobra si el arquero agarra con la mano un pase con el pie de un compañero?", o: ["Tiro libre indirecto", "Penal", "Tiro libre directo", "Nada, es legal"] },
        { p: "¿Cuánto puede durar como máximo el entretiempo, según el reglamento?", o: ["15 minutos", "10 minutos", "20 minutos", "30 minutos"] },
      ],
      400: [
        { p: "¿De cuál de estas jugadas NO puede haber offside si se recibe directamente?", o: ["Saque de arco", "Tiro libre", "Pase hacia adelante", "Rebote en el travesaño"] },
        { p: "¿Cuánto debe medir la circunferencia de la pelota oficial?", o: ["Entre 68 y 70 cm", "Entre 60 y 62 cm", "Entre 75 y 78 cm", "Entre 64 y 66 cm"] },
        { p: "¿Qué organismo decide los cambios en las reglas del fútbol?", o: ["IFAB", "CONMEBOL", "UEFA", "COI"] },
        { p: "¿Cuánto mide el radio del círculo central?", o: ["9,15 metros", "11 metros", "10 metros", "8 metros"] },
        { p: "¿Qué se cobra si quien hace el saque inicial toca la pelota dos veces seguidas?", o: ["Tiro libre indirecto", "Se repite el saque", "Penal", "Tiro libre directo"] },
      ],
      500: [
        { p: "¿En qué año se escribió en Inglaterra el primer reglamento del fútbol moderno?", o: ["1863", "1888", "1904", "1848"] },
        { p: "¿Cuánto debe pesar la pelota oficial al comienzo del partido?", o: ["Entre 410 y 450 gramos", "Entre 300 y 350 gramos", "Entre 500 y 550 gramos", "Entre 360 y 400 gramos"] },
        { p: "¿En qué Mundial se usó el VAR por primera vez?", o: ["Rusia 2018", "Brasil 2014", "Qatar 2022", "Sudáfrica 2010"] },
        { p: "¿Desde qué año el gol de visitante dejó de valer doble en las copas de la UEFA?", o: ["2021", "2018", "2015", "2023"] },
        { p: "¿Cuántas reglas tiene el reglamento oficial del fútbol?", o: ["17", "11", "21", "15"] },
      ],
    },
  },
];
